---
title: "P_xuthus"
author: "Khadijah Amarah Moosa"
date: "2025-02-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



``` {r}
# Load the data
data <- read.csv("Papilio_xuthusRawData.csv")

# Check the first few rows and structure of the data
head(data)
str(data)
```




``` {r}
# Load the data (ensure the correct path or file is specified)
data <- read.csv("Papilio_xuthusRawData.csv")

# Check the first few rows and structure of the data
head(data)
str(data)
```
``` {r}
# Check the structure of your data to see if you have coordinates
str(data)
```
``` {r}
# Load libraries
library(sf)
library(leaflet)
library(ggplot2)
```

``` {r}
# Assuming your CSV has 'lat' and 'long' columns
data_sf <- sf::st_as_sf(data, coords = c("longitude", "latitude"), crs = 4326)


sum(is.na(data_sf$longitude))  # Count missing longitude values
sum(is.na(data_sf$latitude))   # Count missing latitude values

```



```{r}
colnames(data_sf)
```


``` {r}
library(sf)
```

``` {r}
# Convert the data to a spatial object
data_sf <- st_as_sf(data, coords = c("longitude", "latitude"), crs = 4326)

```

``` {r}
# Load the leaflet library
library(leaflet)

# Create an interactive map
leaflet(data) %>%
  addTiles() %>%
  addCircleMarkers(~longitude, ~latitude, color = ~species, popup = ~species)
```
``` {r}
# Check the column names in your spatial object
colnames(data_sf)
```
``` {r}
library(leaflet)

# Create an interactive map
leaflet(data_sf) %>%
  addTiles() %>%
  addCircleMarkers(popup = ~species)
```
``` {r}
library(leaflet)

# Create an interactive map with English labels
leaflet(data_sf) %>%
  addTiles(urlTemplate = "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png") %>%
  addCircleMarkers(popup = ~species)
```







